name: Deploy Node.js to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: appobservability-gxa0gkg2gdgcdthu
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: npm install and build
        run: |
          npm ci
          npm run build

      - name: Add web.config to dist
        run: |
          cp public/web.config dist/

      - name: Add startup command
        run: |
          echo '{ "scripts": { "start": "serve -s" }, "dependencies": { "serve": "^14.0.0" } }' > dist/package.json
          cd dist && npm install

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./dist
          clean: true
